theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true  
  breadcrumb:
    position: hero-end
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"  
  posts:
    default_image: true
    index:
      layout: list
  pages:
    index:
      layout: list
  image_sizes:
    design_system:
      lightbox:
        disabled: true
    blocks:
      call_to_action:
        mobile:   500
        tablet:   800
        desktop:  2000
    sections:
      home:
        hero:
          mobile:   500
          tablet:   800
          desktop:  2000
      pages:
        hero:
          mobile:   500
          tablet:   800
          desktop:  2000
      persons:
        hero_single:
          mobile:   500
          tablet:   1000
          desktop:  415