theme: osuny
_merge: deep
params:
  plausible: postgrowth-lab.webs.uvigo.es
  summary:
    position: hero
  search:
    active: true  
  breadcrumb:
    position: hero-end
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"  
  posts:
    default_image: true
    index:
      layout: list
  pages:
    index:
      layout: list
  publications:
    index:
      group_by_year: true
  components:
    lightbox:
      disabled: true
  image_sizes:
    blocks:
      call_to_action:
        mobile:   500
        tablet:   800
        desktop:  2000
    sections:
      home:
        hero:
          mobile:   500
          tablet:   800
          desktop:  2000
      pages:
        hero:
          mobile:   500
          tablet:   800
          desktop:  2000
      persons:
        hero_single:
          mobile:   500
          tablet:   1000
          desktop:  415